# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: docs

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: debug-statements
  - id: mixed-line-ending
    args: ['--fix=lf']

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [
      --in-place,
      --remove-all-unused-imports,
      --remove-unused-variables,
    ]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-docstrings]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.15.1
  hooks:
    - id: check-github-actions
    - id: check-github-workflows
