name: Update documentation on GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Build documentation with tox
        run: tox -e docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: docs
          folder: docs/new_project_name

      - name: Add the the latest docs back to the repo
        uses: EndBug/add-and-commit@v9
        with:
          message: @auto Update docs
          push: --set-upstream origin main
